-- Seed 40 hand-picked items so the game is immediately playable.

insert into toppl.items (prompt, value, unit, category) values
('Taylor Swift Instagram followers', 283000000, 'followers', 'Pop Culture'),
('Cristiano Ronaldo Instagram followers', 643000000, 'followers', 'Pop Culture'),
('Shah Rukh Khan Instagram followers', 47000000, 'followers', 'Pop Culture'),
('Songs Drake has released', 300, 'songs', 'Pop Culture'),
('Songs Taylor Swift has released', 240, 'songs', 'Pop Culture'),
('Career international runs by Sachin Tendulkar', 34357, 'runs', 'Sports'),
('Career international runs by Virat Kohli', 27500, 'runs', 'Sports'),
('Sixes hit by MS Dhoni in IPL career', 240, 'sixes', 'Sports'),
('Sixes hit across an entire IPL season', 1100, 'sixes', 'Sports'),
('Population of Mumbai metro area', 21700000, 'people', 'Geography'),
('Population of Tokyo metro area', 37400000, 'people', 'Geography'),
('Population of Iceland', 380000, 'people', 'Geography'),
('Population of New Zealand', 5200000, 'people', 'Geography'),
('Estimated pigeons in New York City', 1000000, 'birds', 'Geography'),
('Active Uber drivers in London', 50000, 'drivers', 'Industry & Trade'),
('Steps to the top of the Eiffel Tower', 1665, 'steps', 'Geography'),
('Floors in the Empire State Building', 102, 'floors', 'Geography'),
('Floors in the Burj Khalifa', 163, 'floors', 'Geography'),
('Daily visitors to the Taj Mahal', 22000, 'people', 'Geography'),
('Calories in a McDonald''s Big Mac', 563, 'calories', 'Food & Drink'),
('Calories in a Grande Pumpkin Spice Latte', 390, 'calories', 'Food & Drink'),
('McDonald''s restaurants worldwide', 41000, 'stores', 'Industry & Trade'),
('Starbucks locations worldwide', 38000, 'stores', 'Industry & Trade'),
('Coffee cups consumed in Italy per day', 95000000, 'cups', 'Food & Drink'),
('Tea cups consumed in the UK per day', 100000000, 'cups', 'Food & Drink'),
('Cups of chai consumed in India per day', 1400000000, 'cups', 'Food & Drink'),
('iPhones sold worldwide per day on average', 600000, 'phones', 'Technology'),
('Teslas produced worldwide per day', 5000, 'cars', 'Technology'),
('Wikipedia edits made per minute', 350, 'edits', 'Technology'),
('TikTok videos uploaded per minute', 34000, 'videos', 'Technology'),
('Google searches per second', 99000, 'searches', 'Technology'),
('Largest Powerball jackpot in history in dollars', 2040000000, 'dollars', 'Money'),
('Annual US coffee market value in dollars', 90000000000, 'dollars', 'Money'),
('Average cost of an Indian wedding in rupees', 2000000, 'rupees', 'Money'),
('Weight of a blue whale heart in kilograms', 180, 'kg', 'Biology'),
('Weight of an adult human heart in grams', 310, 'grams', 'Biology'),
('Food eaten by an adult elephant per day in kg', 150, 'kg', 'Biology'),
('Weight of a typical ant in milligrams', 4, 'mg', 'Biology'),
('Lego bricks manufactured per second', 1140, 'bricks', 'Industry & Trade'),
('Times the average person blinks per day', 28800, 'blinks', 'Human Behavior');
